webdriver:
  chrome:
    driver: "${WEBDRIVER:chromedriver.exe}"

user-config:
  username: ${SIAKAD_USERNAME}
  password: ${SIAKAD_PASSWORD}

siakad-config:
  home-url: https://siakad.ar-raniry.ac.id/e-mahasiswa/home
  login-url: https://mahasiswa.siakad.ar-raniry.ac.id/login

spring:
  profiles:
    active: ${PROFILE:dev}

selenium:
  verbose: ${VERBOSE:false}
  timeout: ${TIMEOUT:1}
  headless: ${HEADLESS:false}
  args: ${ARGS}

schedule-config: ${SCHEDULE_CONFIG:classpath:schedule-time-config.json}
